uploads = []

[[generated]]
id = "fNRExkD0bsAZviP3x3rfh"
uri = "file://client/public/avatars/nawa-aya/1-default.png"
type = "image"
title = "generated_image"

[[generated]]
id = "CndID2DiE_jkagLIChmp4"
uri = "file://client/public/avatars/nawa-aya/2-cricket.png"
type = "image"
title = "generated_image"

[[generated]]
id = "nUWJZTimEIsa4edbCHabi"
uri = "file://client/public/avatars/nawa-aya/3-school.png"
type = "image"
title = "generated_image"

[[generated]]
id = "rtkV6WjZYC3hSAatnLdMD"
uri = "file://client/public/avatars/nawa-aya/4-eid.png"
type = "image"
title = "generated_image"

[[generated]]
id = "j8sizpi1b7mDAlEAYRhOR"
uri = "file://client/public/avatars/nawa-aya/5-winter.png"
type = "image"
title = "generated_image"

[[generated]]
id = "F_qz6PfxA3B5lh9C4WLSx"
uri = "file://client/public/avatars/nawa-aya/6-street.png"
type = "image"
title = "generated_image"

[[generated]]
id = "yPZoW-IdLB0y_NNjS-o8a"
uri = "file://client/public/avatars/nawa-aya/7-chef.png"
type = "image"
title = "generated_image"

[[generated]]
id = "TcmBxxoiJckhgT73lOefe"
uri = "file://client/public/avatars/nawa-aya/8-hero.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Z4ns9jvorehw6goGG0juA"
uri = "file://client/public/avatars/munna/1-default.png"
type = "image"
title = "generated_image"

[[generated]]
id = "SRoljH8Yma2JFFLKAIccq"
uri = "file://client/public/avatars/munna/2-casanova.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "kprhpA9J8y7_eGOt4KEHU"
uri = "file://docs/THORX_Knowledge_Base_Master.md"
type = "text"
title = "THORX Master Knowledge Base"
